# Tuned
highway-fast-v0:
  n_timesteps: !!float 2e4
  policy: 'MlpPolicy'
  learning_rate: !!float 5e-4
  batch_size: 32
  buffer_size: 15000
  learning_starts: 200
  gamma: 0.8
  target_update_interval: 50
  train_freq: 1
  gradient_steps: 1
  exploration_fraction: 0.7
  policy_kwargs: "dict(net_arch=[256, 256])"

merge-v0:
  n_timesteps: !!float 2e4
  policy: 'MlpPolicy'
  learning_rate: !!float 5e-4
  batch_size: 32
  buffer_size: 15000
  learning_starts: 200
  gamma: 0.8
  target_update_interval: 50
  train_freq: 1
  gradient_steps: 1
  exploration_fraction: 0.7
  policy_kwargs: "dict(net_arch=[256, 256])"

highway-ME-basic-v0:
  n_timesteps: !!float 5e5
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  batch_size: 32
  buffer_size: 15000
  learning_starts: 200
  gamma: 0.8
  target_update_interval: 50
  train_freq: 1
  gradient_steps: 1
  exploration_fraction: 0.7
  policy_kwargs: "dict(net_arch=[256, 256])"

highway-ME-basic-AddRightRewardALL-v0:
  n_timesteps: !!float 5e5
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  batch_size: 32
  buffer_size: 15000
  learning_starts: 200
  gamma: 0.8
  target_update_interval: 50
  train_freq: 1
  gradient_steps: 1
  exploration_fraction: 0.7
  policy_kwargs: "dict(net_arch=[256, 256])"

highway-ME-basic-AddRightReward-v0:
  n_timesteps: !!float 5e5
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-4
  batch_size: 32
  buffer_size: 15000
  learning_starts: 200
  gamma: 0.8
  target_update_interval: 50
  train_freq: 1
  gradient_steps: 1
  exploration_fraction: 0.7
  policy_kwargs: "dict(net_arch=[256, 256])"

CartPole-v1:
  n_timesteps: !!float 5e4
  policy: 'MlpPolicy'
  learning_rate: !!float 2.3e-3
  batch_size: 64
  buffer_size: 100000
  learning_starts: 1000
  gamma: 0.99
  target_update_interval: 10
  train_freq: 256
  gradient_steps: 128
  exploration_fraction: 0.16
  exploration_final_eps: 0.04
  policy_kwargs: "dict(net_arch=[256, 256])"

CartPole-modifed-v1:
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  learning_rate: !!float 2.3e-3
  batch_size: 64
  buffer_size: 100000
  learning_starts: 1000
  gamma: 0.99
  target_update_interval: 10
  train_freq: 256
  gradient_steps: 128
  exploration_fraction: 0.16
  exploration_final_eps: 0.04
  policy_kwargs: "dict(net_arch=[256, 256])"

CartPole-modifed-morecenterall-v1:
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  learning_rate: !!float 2.3e-3
  batch_size: 64
  buffer_size: 100000
  learning_starts: 1000
  gamma: 0.99
  target_update_interval: 10
  train_freq: 256
  gradient_steps: 128
  exploration_fraction: 0.16
  exploration_final_eps: 0.04
  policy_kwargs: "dict(net_arch=[256, 256])"

CartPole-modifed-morecenter-v1:
  n_timesteps: !!float 1e5
  policy: 'MlpPolicy'
  learning_rate: !!float 2.3e-3
  batch_size: 64
  buffer_size: 100000
  learning_starts: 1000
  gamma: 0.99
  target_update_interval: 10
  train_freq: 256
  gradient_steps: 128
  exploration_fraction: 0.16
  exploration_final_eps: 0.04
  policy_kwargs: "dict(net_arch=[256, 256])"