parking-basic-boundary-v0:
  n_timesteps: !!float 8e5
  policy: 'MlpPolicy'
  learning_rate: !!float 1e-3
  buffer_size: 1000000
  batch_size: 256
  gamma: 0.95
  ent_coef: 'auto'
  policy_kwargs: "dict(net_arch=[256, 256, 256])"
  n_envs: 4
  warmstarting_num_timesteps: 100000
  warmstarting_scale: 10

MountainCarContinuous-modifed-lessleft-v0:
  n_timesteps: !!float 100000
  policy: 'MlpPolicy'
  learning_rate: !!float 3e-4
  buffer_size: 50000
  batch_size: 512
  ent_coef: 0.1
  train_freq: 32
  gradient_steps: 32
  gamma: 0.9999
  tau: 0.01
  learning_starts: 0
  use_sde: True
  policy_kwargs: "dict(log_std_init=-3.67, net_arch=[64, 64])"